/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ITokenChopTokenInterface extends ethers.utils.Interface {
  functions: {
    "initialize(address,address,address)": FunctionFragment;
    "setBandAddress(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setBandAddress",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setBandAddress",
    data: BytesLike
  ): Result;

  events: {};
}

export class ITokenChopToken extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ITokenChopTokenInterface;

  functions: {
    initialize(
      base: string,
      quote: string,
      sister: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "initialize(address,address,address)"(
      base: string,
      quote: string,
      sister: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setBandAddress(
      arg0: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setBandAddress(address)"(
      arg0: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  initialize(
    base: string,
    quote: string,
    sister: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "initialize(address,address,address)"(
    base: string,
    quote: string,
    sister: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setBandAddress(
    arg0: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setBandAddress(address)"(
    arg0: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    initialize(
      base: string,
      quote: string,
      sister: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "initialize(address,address,address)"(
      base: string,
      quote: string,
      sister: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setBandAddress(arg0: string, overrides?: CallOverrides): Promise<void>;

    "setBandAddress(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    initialize(
      base: string,
      quote: string,
      sister: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "initialize(address,address,address)"(
      base: string,
      quote: string,
      sister: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setBandAddress(arg0: string, overrides?: Overrides): Promise<BigNumber>;

    "setBandAddress(address)"(
      arg0: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    initialize(
      base: string,
      quote: string,
      sister: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "initialize(address,address,address)"(
      base: string,
      quote: string,
      sister: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setBandAddress(
      arg0: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setBandAddress(address)"(
      arg0: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
