/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface TokenChopFactoryInterface extends ethers.utils.Interface {
  functions: {
    "allSpec(uint256)": FunctionFragment;
    "allStable(uint256)": FunctionFragment;
    "getSpecAddress(address,address)": FunctionFragment;
    "getStableAddress(address,address)": FunctionFragment;
    "poolFactorySetter()": FunctionFragment;
    "specFactory()": FunctionFragment;
    "stableFactory()": FunctionFragment;
    "allPairsLength()": FunctionFragment;
    "createPair(address,address)": FunctionFragment;
    "setPoolFactories(address,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "allSpec",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "allStable",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSpecAddress",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getStableAddress",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "poolFactorySetter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "specFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stableFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allPairsLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createPair",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setPoolFactories",
    values: [string, string]
  ): string;

  decodeFunctionResult(functionFragment: "allSpec", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "allStable", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSpecAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStableAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "poolFactorySetter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "specFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stableFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allPairsLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createPair", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPoolFactories",
    data: BytesLike
  ): Result;

  events: {
    "PairCreated(address,address,address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "PairCreated"): EventFragment;
}

export class TokenChopFactory extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: TokenChopFactoryInterface;

  functions: {
    allSpec(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    "allSpec(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    allStable(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    "allStable(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getSpecAddress(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "getSpecAddress(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getStableAddress(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "getStableAddress(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    poolFactorySetter(overrides?: CallOverrides): Promise<[string]>;

    "poolFactorySetter()"(overrides?: CallOverrides): Promise<[string]>;

    specFactory(overrides?: CallOverrides): Promise<[string]>;

    "specFactory()"(overrides?: CallOverrides): Promise<[string]>;

    stableFactory(overrides?: CallOverrides): Promise<[string]>;

    "stableFactory()"(overrides?: CallOverrides): Promise<[string]>;

    allPairsLength(overrides?: CallOverrides): Promise<[BigNumber]>;

    "allPairsLength()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    createPair(
      _base: string,
      _quote: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "createPair(address,address)"(
      _base: string,
      _quote: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setPoolFactories(
      _stable: string,
      _spec: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setPoolFactories(address,address)"(
      _stable: string,
      _spec: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  allSpec(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "allSpec(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  allStable(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "allStable(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getSpecAddress(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<string>;

  "getSpecAddress(address,address)"(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<string>;

  getStableAddress(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<string>;

  "getStableAddress(address,address)"(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<string>;

  poolFactorySetter(overrides?: CallOverrides): Promise<string>;

  "poolFactorySetter()"(overrides?: CallOverrides): Promise<string>;

  specFactory(overrides?: CallOverrides): Promise<string>;

  "specFactory()"(overrides?: CallOverrides): Promise<string>;

  stableFactory(overrides?: CallOverrides): Promise<string>;

  "stableFactory()"(overrides?: CallOverrides): Promise<string>;

  allPairsLength(overrides?: CallOverrides): Promise<BigNumber>;

  "allPairsLength()"(overrides?: CallOverrides): Promise<BigNumber>;

  createPair(
    _base: string,
    _quote: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "createPair(address,address)"(
    _base: string,
    _quote: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setPoolFactories(
    _stable: string,
    _spec: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setPoolFactories(address,address)"(
    _stable: string,
    _spec: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    allSpec(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    "allSpec(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    allStable(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    "allStable(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getSpecAddress(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "getSpecAddress(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getStableAddress(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "getStableAddress(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<string>;

    poolFactorySetter(overrides?: CallOverrides): Promise<string>;

    "poolFactorySetter()"(overrides?: CallOverrides): Promise<string>;

    specFactory(overrides?: CallOverrides): Promise<string>;

    "specFactory()"(overrides?: CallOverrides): Promise<string>;

    stableFactory(overrides?: CallOverrides): Promise<string>;

    "stableFactory()"(overrides?: CallOverrides): Promise<string>;

    allPairsLength(overrides?: CallOverrides): Promise<BigNumber>;

    "allPairsLength()"(overrides?: CallOverrides): Promise<BigNumber>;

    createPair(
      _base: string,
      _quote: string,
      overrides?: CallOverrides
    ): Promise<[string, string] & { stable: string; spec: string }>;

    "createPair(address,address)"(
      _base: string,
      _quote: string,
      overrides?: CallOverrides
    ): Promise<[string, string] & { stable: string; spec: string }>;

    setPoolFactories(
      _stable: string,
      _spec: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setPoolFactories(address,address)"(
      _stable: string,
      _spec: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    PairCreated(
      base: string | null,
      quote: string | null,
      stable: null,
      spec: null,
      undefined: null
    ): EventFilter;
  };

  estimateGas: {
    allSpec(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "allSpec(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    allStable(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "allStable(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSpecAddress(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getSpecAddress(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getStableAddress(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getStableAddress(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    poolFactorySetter(overrides?: CallOverrides): Promise<BigNumber>;

    "poolFactorySetter()"(overrides?: CallOverrides): Promise<BigNumber>;

    specFactory(overrides?: CallOverrides): Promise<BigNumber>;

    "specFactory()"(overrides?: CallOverrides): Promise<BigNumber>;

    stableFactory(overrides?: CallOverrides): Promise<BigNumber>;

    "stableFactory()"(overrides?: CallOverrides): Promise<BigNumber>;

    allPairsLength(overrides?: CallOverrides): Promise<BigNumber>;

    "allPairsLength()"(overrides?: CallOverrides): Promise<BigNumber>;

    createPair(
      _base: string,
      _quote: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "createPair(address,address)"(
      _base: string,
      _quote: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setPoolFactories(
      _stable: string,
      _spec: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setPoolFactories(address,address)"(
      _stable: string,
      _spec: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    allSpec(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "allSpec(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    allStable(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "allStable(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSpecAddress(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getSpecAddress(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getStableAddress(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getStableAddress(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    poolFactorySetter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "poolFactorySetter()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    specFactory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "specFactory()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    stableFactory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "stableFactory()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    allPairsLength(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "allPairsLength()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createPair(
      _base: string,
      _quote: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "createPair(address,address)"(
      _base: string,
      _quote: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setPoolFactories(
      _stable: string,
      _spec: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setPoolFactories(address,address)"(
      _stable: string,
      _spec: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
