/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface TokenChopStableFactoryInterface extends ethers.utils.Interface {
  functions: {
    "bandAddr()": FunctionFragment;
    "factory()": FunctionFragment;
    "createPool(address,address)": FunctionFragment;
    "initialize(address,address,address,address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "bandAddr", values?: undefined): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createPool",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string, string, string]
  ): string;

  decodeFunctionResult(functionFragment: "bandAddr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createPool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;

  events: {};
}

export class TokenChopStableFactory extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: TokenChopStableFactoryInterface;

  functions: {
    bandAddr(overrides?: CallOverrides): Promise<[string]>;

    "bandAddr()"(overrides?: CallOverrides): Promise<[string]>;

    factory(overrides?: CallOverrides): Promise<[string]>;

    "factory()"(overrides?: CallOverrides): Promise<[string]>;

    createPool(
      _base: string,
      _quote: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "createPool(address,address)"(
      _base: string,
      _quote: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    initialize(
      _base: string,
      _quote: string,
      _stable: string,
      _spec: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "initialize(address,address,address,address)"(
      _base: string,
      _quote: string,
      _stable: string,
      _spec: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  bandAddr(overrides?: CallOverrides): Promise<string>;

  "bandAddr()"(overrides?: CallOverrides): Promise<string>;

  factory(overrides?: CallOverrides): Promise<string>;

  "factory()"(overrides?: CallOverrides): Promise<string>;

  createPool(
    _base: string,
    _quote: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "createPool(address,address)"(
    _base: string,
    _quote: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  initialize(
    _base: string,
    _quote: string,
    _stable: string,
    _spec: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "initialize(address,address,address,address)"(
    _base: string,
    _quote: string,
    _stable: string,
    _spec: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    bandAddr(overrides?: CallOverrides): Promise<string>;

    "bandAddr()"(overrides?: CallOverrides): Promise<string>;

    factory(overrides?: CallOverrides): Promise<string>;

    "factory()"(overrides?: CallOverrides): Promise<string>;

    createPool(
      _base: string,
      _quote: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "createPool(address,address)"(
      _base: string,
      _quote: string,
      overrides?: CallOverrides
    ): Promise<string>;

    initialize(
      _base: string,
      _quote: string,
      _stable: string,
      _spec: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "initialize(address,address,address,address)"(
      _base: string,
      _quote: string,
      _stable: string,
      _spec: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    bandAddr(overrides?: CallOverrides): Promise<BigNumber>;

    "bandAddr()"(overrides?: CallOverrides): Promise<BigNumber>;

    factory(overrides?: CallOverrides): Promise<BigNumber>;

    "factory()"(overrides?: CallOverrides): Promise<BigNumber>;

    createPool(
      _base: string,
      _quote: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "createPool(address,address)"(
      _base: string,
      _quote: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    initialize(
      _base: string,
      _quote: string,
      _stable: string,
      _spec: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "initialize(address,address,address,address)"(
      _base: string,
      _quote: string,
      _stable: string,
      _spec: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    bandAddr(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "bandAddr()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    factory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "factory()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    createPool(
      _base: string,
      _quote: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "createPool(address,address)"(
      _base: string,
      _quote: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _base: string,
      _quote: string,
      _stable: string,
      _spec: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "initialize(address,address,address,address)"(
      _base: string,
      _quote: string,
      _stable: string,
      _spec: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
