/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { ITokenChopPoolFactory } from "../ITokenChopPoolFactory";

export class ITokenChopPoolFactory__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITokenChopPoolFactory {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ITokenChopPoolFactory;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_base",
        type: "address",
      },
      {
        internalType: "address",
        name: "_quote",
        type: "address",
      },
    ],
    name: "createPool",
    outputs: [
      {
        internalType: "address",
        name: "poolAddr",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_base",
        type: "address",
      },
      {
        internalType: "address",
        name: "_quote",
        type: "address",
      },
      {
        internalType: "address",
        name: "_poolAddr",
        type: "address",
      },
      {
        internalType: "address",
        name: "_sisterAddr",
        type: "address",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
